// Expanded French vocabulary - 200 words with pronunciation
export const frenchVocabulary = [
  // Greetings & Basics (1-30)
  { french: 'Bonjour', pronunciation: 'bon-ZHOOR', english: 'Hello' },
  { french: 'Bonsoir', pronunciation: 'bon-SWAHR', english: 'Good evening' },
  { french: 'Au revoir', pronunciation: 'oh ruh-VWAHR', english: 'Goodbye' },
  { french: 'Salut', pronunciation: 'sah-LUU', english: 'Hi/Bye' },
  { french: 'Merci', pronunciation: 'mair-SEE', english: 'Thank you' },
  { french: 'Merci beaucoup', pronunciation: 'mair-SEE boh-KOO', english: 'Thank you very much' },
  { french: "De rien", pronunciation: 'duh ree-EN', english: "You're welcome" },
  { french: "S'il vous plaît", pronunciation: 'seel voo PLEH', english: 'Please' },
  { french: 'Excusez-moi', pronunciation: 'ex-koo-ZAY mwah', english: 'Excuse me' },
  { french: 'Pardon', pronunciation: 'par-DON', english: 'Sorry' },
  { french: 'Oui', pronunciation: 'WEE', english: 'Yes' },
  { french: 'Non', pronunciation: 'NOH', english: 'No' },
  { french: 'Peut-être', pronunciation: 'puh-TET-ruh', english: 'Maybe' },
  { french: 'Bien sûr', pronunciation: 'bee-en SOOR', english: 'Of course' },
  { french: 'Daccord', pronunciation: 'dah-KOR', english: 'OK/Agreed' },
  { french: 'Comment?', pronunciation: 'koh-MAHN', english: 'What?/How?' },
  { french: 'Pourquoi?', pronunciation: 'poor-KWAH', english: 'Why?' },
  { french: 'Oú?', pronunciation: 'OO', english: 'Where?' },
  { french: 'Qui?', pronunciation: 'KEE', english: 'Who?' },
  { french: 'Quand?', pronunciation: 'KAHN', english: 'When?' },
  { french: 'Combien?', pronunciation: 'kom-BEE-en', english: 'How much?' },
  { french: 'Quoi?', pronunciation: 'KWAH', english: 'What?' },
  { french: 'Quel?', pronunciation: 'KEL', english: 'Which?' },
  { french: 'Comment vous appelez-vous?', pronunciation: 'koh-MAHN voo zah-puh-LAY voo', english: 'What is your name?' },
  { french: 'Je mappelle...', pronunciation: 'zhuh mah-PEL', english: 'My name is...' },
  { french: 'Enchanté', pronunciation: 'ahn-shahn-TAY', english: 'Nice to meet you' },
  { french: 'Comment allez-vous?', pronunciation: 'koh-MAHN tah-LAY voo', english: 'How are you?' },
  { french: 'Ça va bien', pronunciation: 'sah VAH bee-en', english: 'I\'m good' },
  { french: 'Ça va mal', pronunciation: 'sah VAH MAHL', english: 'Not good' },
  { french: 'Et vous?', pronunciation: 'ay VOO', english: 'And you?' },

  // Directions (31-50)
  { french: 'À gauche', pronunciation: 'ah GOHSH', english: 'To the left' },
  { french: 'À droite', pronunciation: 'ah DRWAHT', english: 'To the right' },
  { french: 'Tout droit', pronunciation: 'too DRWAH', english: 'Straight ahead' },
  { french: 'Là-bas', pronunciation: 'lah-BAH', english: 'Over there' },
  { french: 'Ici', pronunciation: 'ee-SEE', english: 'Here' },
  { french: 'Là', pronunciation: 'LAH', english: 'There' },
  { french: 'En haut', pronunciation: 'ahn OH', english: 'Upstairs' },
  { french: 'En bas', pronunciation: 'ahn BAH', english: 'Downstairs' },
  { french: 'Devant', pronunciation: 'duh-VAHN', english: 'In front' },
  { french: 'Derrière', pronunciation: 'dair-ee-AIR', english: 'Behind' },
  { french: 'À côté', pronunciation: 'ah koh-TAY', english: 'Next to' },
  { french: 'Entre', pronunciation: 'AHN-truh', english: 'Between' },
  { french: 'Le nord', pronunciation: 'luh NOR', english: 'North' },
  { french: 'Le sud', pronunciation: 'luh SOOD', english: 'South' },
  { french: 'L\'est', pronunciation: 'LEST', english: 'East' },
  { french: 'L\'ouest', pronunciation: 'LOO-EST', english: 'West' },
  { french: 'La sortie', pronunciation: 'lah sor-TEE', english: 'Exit' },
  { french: 'L\'entrée', pronunciation: 'lahn-TRAY', english: 'Entrance' },
  { french: 'Le coin', pronunciation: 'luh KWAN', english: 'The corner' },
  { french: 'La rue', pronunciation: 'lah ROO', english: 'The street' },

  // Travel & Transport (51-80)
  { french: 'Le métro', pronunciation: 'luh may-TROH', english: 'Subway/Metro' },
  { french: 'La gare', pronunciation: 'lah GAHR', english: 'Train station' },
  { french: 'L\'aéroport', pronunciation: 'lay-ay-roh-POR', english: 'Airport' },
  { french: 'Le bus', pronunciation: 'luh BOOS', english: 'Bus' },
  { french: 'Le taxi', pronunciation: 'luh tak-SEE', english: 'Taxi' },
  { french: 'Le train', pronunciation: 'luh TRAN', english: 'Train' },
  { french: 'Le billet', pronunciation: 'luh bee-YAY', english: 'Ticket' },
  { french: 'La valise', pronunciation: 'lah vah-LEEZ', english: 'Suitcase' },
  { french: 'Le passeport', pronunciation: 'luh pahs-POR', english: 'Passport' },
  { french: 'La gare', pronunciation: 'lah GAHR', english: 'Station' },
  { french: 'Le quai', pronunciation: 'luh KAY', english: 'Platform' },
  { french: 'Le départ', pronunciation: 'luh day-PAR', english: 'Departure' },
  { french: 'L\'arrivée', pronunciation: 'lah-ree-VAY', english: 'Arrival' },
  { french: 'En retard', pronunciation: 'ahn ruh-TAR', english: 'Late' },
  { french: 'À l\'heure', pronunciation: 'ah LURE', english: 'On time' },
  { french: 'Un billet aller-retour', pronunciation: 'un bee-YAY ah-LAY ruh-TOOR', english: 'Round-trip ticket' },
  { french: 'Première classe', pronunciation: 'pruh-MYEHR klahs', english: 'First class' },
  { french: 'Deuxième classe', pronunciation: 'duh-ZYEM klahs', english: 'Second class' },
  { french: 'La乘客', pronunciation: 'lah SHAHN-zhuh', english: 'Passenger' },
  { french: 'Le wagon', pronunciation: 'luh vah-GON', english: 'Carriage' },
  { french: 'La place', pronunciation: 'lah PLAHS', english: 'Seat' },
  { french: 'Réservé', pronunciation: 'ray-zair-VAY', english: 'Reserved' },
  { french: 'Non-fumeur', pronunciation: 'nohn fuh-MURE', english: 'No smoking' },
  { french: 'Fumeur', pronunciation: 'fuh-MURE', english: 'Smoking' },
  { french: 'Le parking', pronunciation: 'luh par-KEENG', english: 'Parking' },
  { french: 'La station-service', pronunciation: 'lah stah-SYON sair-VEES', english: 'Gas station' },
  { french: 'L\'essence', pronunciation: 'leh-SAHNS', english: 'Gasoline' },
  { french: 'Le plein', pronunciation: 'luh PLAN', english: 'Full tank' },
  { french: 'La location de voiture', pronunciation: 'lah loh-kah-SYON duh vwah-TOOR', english: 'Car rental' },

  // Food & Dining (81-120)
  { french: 'Le restaurant', pronunciation: 'luh res-toh-RAHN', english: 'Restaurant' },
  { french: 'Le café', pronunciation: 'luh kah-FAY', english: 'Coffee shop/Café' },
  { french: 'Le petit-déjeuner', pronunciation: 'luh puh-TEE day-zhuh-NAY', english: 'Breakfast' },
  { french: 'Le déjeuner', pronunciation: 'luh day-zhuh-NAY', english: 'Lunch' },
  { french: 'Le dîner', pronunciation: 'luh dee-NAY', english: 'Dinner' },
  { french: 'L\'addition', pronunciation: 'lah-dee-SYON', english: 'The bill' },
  { french: 'Le menu', pronunciation: 'luh muh-NOO', english: 'Menu' },
  { french: 'La carte', pronunciation: 'lah KAHRT', english: 'The menu' },
  { french: 'Eau', pronunciation: 'OH', english: 'Water' },
  { french: 'Le vin', pronunciation: 'luh VAN', english: 'Wine' },
  { french: 'La bière', pronunciation: 'lah BYEHR', english: 'Beer' },
  { french: 'Le café', pronunciation: 'luh kah-FAY', english: 'Coffee' },
  { french: 'Le thé', pronunciation: 'luh TAY', english: 'Tea' },
  { french: 'Le lait', pronunciation: 'luh LAY', english: 'Milk' },
  { french: 'Le sucre', pronunciation: 'luh SOO-kruh', english: 'Sugar' },
  { french: 'Sans sucre', pronunciation: 'sahn SOO-kruh', english: 'No sugar' },
  { french: 'L\'addition', pronunciation: 'lah-dee-SYON', english: 'Check please' },
  { french: 'C\'est délicieux', pronunciation: 'say day-lee-SYUH', english: 'Delicious' },
  { french: 'J\'ai faim', pronunciation: 'zhay FAM', english: 'I\'m hungry' },
  { french: 'J\'ai soif', pronunciation: 'zhay SWAHF', english: 'I\'m thirsty' },
  { french: 'Je suis végétarien', pronunciation: 'zhuh swee vay-zhay-tah-RYAN', english: 'I\'m vegetarian' },
  { french: 'Allergique à...', pronunciation: 'ah-lair-ZHEEK ah', english: 'Allergic to...' },
  { french: 'Sans gluten', pronunciation: 'sahn GLOO-ten', english: 'Gluten-free' },
  { french: 'Le plats', pronunciation: 'luh PLAH', english: 'Dish' },
  { french: 'L\'entrée', pronunciation: 'lahn-TRAY', english: 'Starter' },
  { french: 'Le plat principal', pronunciation: 'luh PLAH pran-see-PAHL', english: 'Main course' },
  { french: 'Le dessert', pronunciation: 'luh day-SAIR', english: 'Dessert' },
  { french: 'Un croissant', pronunciation: 'un kruh-SAHN', english: 'Croissant' },
  { french: 'Une baguette', pronunciation: 'oon bah-GET', english: 'Baguette' },
  { french: 'Le fromage', pronunciation: 'luh froh-MAHZH', english: 'Cheese' },
  { french: 'Le beurre', pronunciation: 'luh BUR', english: 'Butter' },
  { french: 'La confiture', pronunciation: 'lah kohn-fee-TOOR', english: 'Jam' },
  { french: 'Les œufs', pronunciation: 'lay UHF', english: 'Eggs' },
  { french: 'Le bacon', pronunciation: 'luh bay-KON', english: 'Bacon' },
  { french: 'Les pancakes', pronunciation: 'lay PAHNK', english: 'Pancakes' },
  { french: 'L\'omelette', pronunciation: 'lohm-LET', english: 'Omelette' },
  { french: 'Les pommes de terre', pronunciation: 'lay pom duh TAIR', english: 'Potatoes' },
  { french: 'La salade', pronunciation: 'lah sah-LAHD', english: 'Salad' },
  { french: 'Le poulet', pronunciation: 'luh poo-LAY', english: 'Chicken' },
  { french: 'Le bœuf', pronunciation: 'luh BUF', english: 'Beef' },
  { french: 'Le porc', pronunciation: 'luh POR', english: 'Pork' },
  { french: 'Le poisson', pronunciation: 'luh pwah-SON', english: 'Fish' },

  // Shopping & Money (121-150)
  { french: 'L\'argent', pronunciation: 'lahr-ZHAHN', english: 'Money' },
  { french: 'La carte de crédit', pronunciation: 'lah KAHRT duh kray-DEE', english: 'Credit card' },
  { french: 'Les espèces', pronunciation: 'lay zes-PES', english: 'Cash' },
  { french: 'Le prix', pronunciation: 'luh PREE', english: 'Price' },
  { french: 'C\'est combien?', pronunciation: 'say kom-BEE-en', english: 'How much is it?' },
  { french: 'Trop cher', pronunciation: 'troh SHAIR', english: 'Too expensive' },
  { french: 'Une réduction', pronunciation: 'oon ray-dook-SYON', english: 'A discount' },
  { french: 'La boutique', pronunciation: 'lah boo-TEEK', english: 'Shop/Store' },
  { french: 'Le centre commercial', pronunciation: 'luh SAHN-truh koh-mair-SYAL', english: 'Shopping center' },
  { french: 'Le marché', pronunciation: 'luh mar-SHAY', english: 'Market' },
  { french: 'Les soldes', pronunciation: 'lay SOHLD', english: 'Sales' },
  { french: 'La robe', pronunciation: 'lah ROB', english: 'Dress' },
  { french: 'La chemise', pronunciation: 'lah shuh-MEEZ', english: 'Shirt' },
  { french: 'Le pantalons', pronunciation: 'luh pahn-tah-LOH', english: 'Pants' },
  { french: 'Les chaussure', pronunciation: 'lay shoh-SOOR', english: 'Shoes' },
  { french: 'La taille', pronunciation: 'lah TAHY', english: 'Size' },
  { french: 'Trop petit', pronunciation: 'troh puh-TEE', english: 'Too small' },
  { french: 'Trop grand', pronunciation: 'troh GRAHN', english: 'Too big' },
  { french: 'Ça me va', pronunciation: 'sah muh VAH', english: 'It fits me' },
  { french: 'Je le prends', pronunciation: 'zhuh luh PRAHN', english: 'I\'ll take it' },
  { french: 'Acceptez-vous...?', pronunciation: 'ahk-sep-TAY voo', english: 'Do you accept...?' },
  { french: 'Le reçu', pronunciation: 'luh ruh-SOO', english: 'Receipt' },
  { french: 'La monnaie', pronunciation: 'lah moh-NAY', english: 'Change' },
  { french: 'Le sac', pronunciation: 'luh SAHK', english: 'Bag' },
  { french: 'L\'emballage', pronunciation: 'lahm-bah-LAHZH', english: 'Packaging' },
  { french: 'Une garantie', pronunciation: 'oon gahr-ahn-TEE', english: 'Warranty' },
  { french: 'Ouvert', pronunciation: 'oo-VAIR', english: 'Open' },
  { french: 'Fermé', pronunciation: 'fair-MAY', english: 'Closed' },
  { french: 'Les heures d\'ouverture', pronunciation: 'lay ZURE duh-vair-TOOR', english: 'Opening hours' },

  // Common Phrases (151-180)
  { french: 'Je ne comprends pas', pronunciation: 'zhuh nuh kohm-PRAHN pah', english: 'I don\'t understand' },
  { french: 'Parlez-vous anglais?', pronunciation: 'par-LAY voo on-GLEH', english: 'Do you speak English?' },
  { french: 'Un peu', pronunciation: 'un PUH', english: 'A little' },
  { french: 'Je ne parle pas français', pronunciation: 'zhuh nuh PARL pah frahn-SAY', english: 'I don\'t speak French' },
  { french: 'Parlez plus lentement', pronunciation: 'par-LAY ploo lahn-tuh-MAHN', english: 'Speak slower please' },
  { french: 'Pouvez-vous m\'aider?', pronunciation: 'poo-vay VOO mah-ee-DAY', english: 'Can you help me?' },
  { french: 'Je suis perdu', pronunciation: 'zhuh swee pair-DOO', english: 'I\'m lost' },
  { french: 'Oú est...?', pronunciation: 'oo EH', english: 'Where is...?' },
  { french: 'C\'est loin?', pronunciation: 'seh LWAN', english: 'Is it far?' },
  { french: 'L\'adresse, s\'il vous plaît', pronunciation: 'lah-DRESS seel voo PLEH', english: 'The address, please' },
  { french: 'Le téléphone', pronunciation: 'luh tay-lay-FON', english: 'Telephone' },
  { french: 'L\'hôpital', pronunciation: 'loh-pee-TAHL', english: 'Hospital' },
  { french: 'La pharmacie', pronunciation: 'lah far-mah-SEE', english: 'Pharmacy' },
  { french: 'La police', pronunciation: 'lah poh-LEES', english: 'Police' },
  { french: 'Les urgences', pronunciation: 'lay oor-ZHAHNS', english: 'Emergency' },
  { french: 'J\'ai besoin d\'aide', pronunciation: 'zhay buh-ZWAN DED', english: 'I need help' },
  { french: 'Je suis malade', pronunciation: 'zhuh swee mah-LAHD', english: 'I\'m sick' },
  { french: 'Le médecin', pronunciation: 'luh mayd-SAN', english: 'Doctor' },
  { french: 'L\'ambulance', pronunciation: 'lahm-boo-LAHNS', english: 'Ambulance' },
  { french: 'Je ne me sens pas bien', pronunciation: 'zhuh nuh muh SAHN pah bee-EN', english: 'I don\'t feel well' },
  { french: 'La salle de bain', pronunciation: 'lah SAHL duh BAN', english: 'Bathroom' },
  { french: 'Les toilettes', pronunciation: 'lay twah-LET', english: 'Toilet' },
  { french: 'Oú sont les toilettes?', pronunciation: 'oo sohn lay twah-LET', english: 'Where is the toilet?' },
  { french: 'Je voudrais...', pronunciation: 'zhuh voo-DRAY', english: 'I would like...' },
  { french: 'Avez-vous...?', pronunciation: 'ah-vay VOO', english: 'Do you have...?' },
  { french: 'Je cherche...', pronunciation: 'zhuh SHAIRSH', english: 'I\'m looking for...' },
  { french: 'C\'est à vendre?', pronunciation: 'say tah VAHN-druh', english: 'Is it for sale?' },
  { french: 'Je peux payer par carte?', pronunciation: 'zhuh PUH pay-YAY par KAHRT', english: 'Can I pay by card?' },
  { french: 'Où puis-je trouver...?', pronunciation: 'oo pwee-zhuh troo-VAY', english: 'Where can I find...?' },
  { french: 'Je reviens', pronunciation: 'zhuh ruh-VYEN', english: 'I\'ll be back' },

  // Question Words (181-200)
  { french: 'Qui?', pronunciation: 'KEE', english: 'Who?' },
  { french: 'Quoi?', pronunciation: 'KWAH', english: 'What?' },
  { french: 'Oú?', pronunciation: 'OO', english: 'Where?' },
  { french: 'Quand?', pronunciation: 'KAHN', english: 'When?' },
  { french: 'Pourquoi?', pronunciation: 'poor-KWAH', english: 'Why?' },
  { french: 'Comment?', pronunciation: 'koh-MAHN', english: 'How?' },
  { french: 'Lequel?', pronunciation: 'luh-KEL', english: 'Which one?' },
  { french: 'Combien?', pronunciation: 'kom-BEE-en', english: 'How many/much?' },
  { french: 'Quel?', pronunciation: 'KEL', english: 'What/Which (masc)' },
  { french: 'Quelle?', pronunciation: 'KEL', english: 'What/Which (fem)' },
  { french: 'Quels?', pronunciation: 'KEL', english: 'What/Which (masc plural)' },
  { french: 'Quelles?', pronunciation: 'KEL', english: 'What/Which (fem plural)' },
  { french: 'À qui?', pronunciation: 'ah KEE', english: 'To whom?' },
  { french: 'De qui?', pronunciation: 'duh KEE', english: 'Of/from whom?' },
  { french: 'Depuis quand?', pronunciation: 'duh-PWEE KAHN', english: 'Since when?' },
  { french: 'Pendant combien de temps?', pronunciation: 'pahn-DAHN kom-BEE-en duh TAHN', english: 'For how long?' },
  { french: 'Comment ça va?', pronunciation: 'koh-MAHN sah VAH', english: 'How\'s it going?' },
  { french: 'Pourquoi pas?', pronunciation: 'poor-KWAH PAH', english: 'Why not?' },
  { french: 'Quel temps fait-il?', pronunciation: 'kel TAHN fay-TEEL', english: 'What\'s the weather like?' },
  { french: 'Quelle heure est-il?', pronunciation: 'kel UHR eh-TEEL', english: 'What time is it?' },
];

export const frenchVerbs = [
  { verb: 'être', meaning: 'to be', present: 'je suis, tu es, il est, nous sommes, vous êtes, ils sont' },
  { verb: 'avoir', meaning: 'to have', present: 'j\'ai, tu as, il a, nous avons, vous avez, ils ont' },
  { verb: 'aller', meaning: 'to go', present: 'je vais, tu vas, il va, nous allons, vous allez, ils vont' },
  { verb: 'faire', meaning: 'to do/make', present: 'je fais, tu fais, il fait, nous faisons, vous faites, ils font' },
  { verb: 'venir', meaning: 'to come', present: 'je viens, tu viens, il vient, nous venons, vous venez, ils viennent' },
  { verb: 'voir', meaning: 'to see', present: 'je vois, tu vois, il voit, nous voyons, vous voyez, ils voient' },
  { verb: 'savoir', meaning: 'to know', present: 'je sais, tu sais, il sait, nous savons, vous savez, ils savent' },
  { verb: 'vouloir', meaning: 'to want', present: 'je veux, tu veux, il veut, nous voulons, vous voulez, ils veulent' },
  { verb: 'pouvoir', meaning: 'can/to be able', present: 'je peux, tu peux, il peut, nous pouvons, vous pouvez, ils peuvent' },
  { verb: 'dire', meaning: 'to say/tell', present: 'je dis, tu dis, il dit, nous disons, vous dites, ils disent' },
  { verb: 'prendre', meaning: 'to take', present: 'je prends, tu prends, il prend, nous prenons, vous prenez, ils prennent' },
  { verb: 'parler', meaning: 'to speak', present: 'je parle, tu parles, il parle, nous parlons, vous parlez, ils parlent' },
];
